fix: Defer content rendition changes during ads
muxinc/stats-sdk-android pull request #76
Opened 2024-11-27 20:33 UTC by daytime-em

2024-12-04 16:18 UTC, cjpillsbury requested changes
One minor ask on the tests. Otherwise, LGTM!

2024-12-04 17:34 UTC, daytime-em commented on library/src/test/java/com/mux/core_android/StateCollectorTests.kt
> +    stateCollector.renditionChange(
Good idea. I'll def do that

2024-12-05 18:33 UTC, daytime-em commented
@cjpillsbury I updated the tests to cover subsequent renditionchange events

2024-12-11 17:11 UTC, cjpillsbury approved these changes

2024-12-11 17:17 UTC, merged